export default image = {
  m1: require("./../assets/images/m1.jpg"),
  m2: require("./../assets/images/m2.jpg"),
  m3: require("./../assets/images/m3.jpg"),
  m4: require("./../assets/images/m4.jpeg"),
  m5: require("./../assets/images/m5.jpeg"),
  m6: require("./../assets/images/m6.jpg"),
  m7: require("./../assets/images/m7.jpg"),
  intro1: require("./../assets/images/intro1.png"),
  intro2: require("./../assets/images/intro2.png"),
  intro3: require("./../assets/images/intro3.png"),
  leftBottom: require("./../assets/images/leftBottom.png"),
  rightBottom: require("./../assets/images/rightBottom.png"),
  splashScreen: require("./../assets/images/splashScreen.jpg"),
  user: require("./../assets/images/user.png"),

  // ------------- All Icon Assets --------------------
  activityIcon: require("./../assets/icons/activity.png"),
  doubleHeartIcon: require("./../assets/icons/doubleHeart.png"),
  allsessionsIcon: require("./../assets/icons/allsessions.png"),
  clockIcon: require("./../assets/icons/clock.png"),
  downloadIcon: require("./../assets/icons/download.png"),
  facebookIcon: require("./../assets/icons/facebook.png"),
  googleIcon: require("./../assets/icons/google.png"),
  icqueuemusicIcon: require("./../assets/icons/icqueuemusic.png"),
  leftarowIcon: require("./../assets/icons/leftarow.png"),
  leftarrowIcon: require("./../assets/icons/leftarrow.png"),
  likeIcon: require("./../assets/icons/like.png"),
  loackIcon: require("./../assets/icons/loack.png"),
  mailIcon: require("./../assets/icons/mail.png"),
  rightarrowIcon: require("./../assets/icons/rightarrow.png"),
  userIcon: require("./../assets/icons/user.png"),
  allsessionsIcon: require("./../assets/icons/allsessions.png"),
  totledurationIcon: require("./../assets/icons/totleduration.png"),
  mygoalIcon: require("./../assets/icons/mygoal.png"),
  timerIcon: require("./../assets/icons/timer.png"),
  topCurveIcon: require("./../assets/icons/topCurve.png"),
  bottomCurveIcon: require("./../assets/icons/bottomCurve.png"),

  // ----------------  Tab-Icon -------------
  feedIcon: require("./../assets/icons/feed.png"),
  meditationIcon: require("./../assets/icons/meditation.png"),
  musicIcon: require("./../assets/icons/music.png"),
  fevoriteIcon: require("./../assets/icons/fevorite.png"),
  profileIcon: require("./../assets/icons/profile.png"),

  // --------------- Profile-Icon ---------------
  progressIcon: require("./../assets/icons/progress.png"),
  reminderIcon: require("./../assets/icons/Reminder.png"),
  notificationIcon: require("./../assets/icons/Notification.png"),
  checkIcon: require("./../assets/icons/check.png"),
  uncheckIcon: require("./../assets/icons/uncheck.png"),
  syncmyprogressIcon: require("./../assets/icons/Syncmyprogress.png"),
  deleteaccountIcon: require("./../assets/icons/Deleteaccount.png"),
  helpIcon: require("./../assets/icons/Help.png"),
  policiesIcon: require("./../assets/icons/Policies.png"),
  logoutIcon: require("./../assets/icons/Logout.png"),

  // --------------- PlayMusic-Icon ---------------
  downloadMusicIcon: require("./../assets/icons/downloadMusic.png"),
  halfMoonIcon: require("./../assets/icons/halfMoon.png"),
  pauseMusicIcon: require("./../assets/icons/pauseMusic.png"),
  nextMusicIcon: require("./../assets/icons/nextMusic.png"),
  previousMusicIcon: require("./../assets/icons/previousMusic.png"),

}